fish_items = [
    {
        'rarity': 1,
        'fish': [
            "Common Trout",
            "Sardine",
            "Catfish",
            "Perch",
            "Goldfish",
            "Plankton",
            "Shrimp",
            "Minnow",
            "Anchovy",
            "Mackerel",
            "Jellyfish",
            "Seaweed",
            "Clam",
            "Starfish",
            "Coral"
        ],
    },
    {
        'rarity': 2,
        'fish': [
            "Salmon",
            "Tuna",
            "Pike",
            "Barracuda",
            "Crab",
            "Lobster",
            "Swordfish",
            "Bass",
            "Oyster",
            "Mullet",
            "Cuttlefish",
            "Squid",
            "Octopus",
            "Seahorse",
            "Coral Reef"
        ],
    },
    {
        'rarity': 3,
        'fish': [
            "Marlin",
            "Mahi-Mahi",
            "Trout King",
            "Red Snapper",
            "King Crab",
            "Angelfish",
            "Clownfish",
            "Flying Fish",
            "Lobster King",
            "Grouper",
            "Electric Eel",
            "Lionfish",
            "Sea Turtle",
            "Jellyfish King",
            "Shipwreck"
        ],
    },
    {
        'rarity': 4,
        'fish': [
            "Great White Shark",
            "Giant Squid",
            "Bluefin Tuna",
            "Hammerhead Shark",
            "Moray Eel",
            "Stonefish",
            "Giant Clam",
            "Humpback Whale",
            "Manta Ray",
            "Barracuda King",
            "Giant Lobster",
            "Killer Whale",
            "Coral Serpent",
            "Sunken Treasure",
            "Kraken"
        ],
    },
    {
        'rarity': 5,
        'fish': [
            "Legendary Fish",
            "Leviathan",
            "Abyssal Anglerfish",
            "Deep Sea Dragon",
            "Neptune's Crown",
            "Celestial Jellyfish",
            "Ghost Shark",
            "Thunder Salmon",
            "Dire Barracuda",
            "Tidal Titan",
            "Volcanic Grouper",
            "Megalodon",
            "Rainbow Mermaid",
            "Cosmic Kraken",
            "Atlantis Relic"
        ],
    },
]
